### ISSUE TITLE
IPNS Records Dag Cbor data fixture

### ISSUE THREAD

**Issue by SionoiS** [ipld/codec-fixtures#75]
Hi,

I was trying to read an IPNS record from Kubo in rust and they don't decode.

Spec -> https://github.com/ipfs/specs/blob/main/ipns/IPNS.md#record-creation

With fixtures I could tell if the problem is on my end or not.

**Comment by rvagg** [comment]
yep, I agree, this would be great! any chance you could help contribute something? if it's not clear how to contribute then I'd love to help make it clearer so I'm not the only one who knows the magic incantations and this repo can serve as more general community resource

**Comment by SionoiS** [comment]
See https://github.com/ipld/codec-fixtures/pull/76
